Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &Supplier
    Name: Supplier
    ID: SupplierMSP
    MSPDir: ./crypto-config/peerOrganizations/supplier.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('SupplierMSP.admin', 'SupplierMSP.client', 'SupplierMSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('SupplierMSP.admin', 'SupplierMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('SupplierMSP.admin')"

  - &Manufacturer
    Name: Manufacturer
    ID: ManufacturerMSP
    MSPDir: ./crypto-config/ordererOrganizations/manufacturer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.client', 'ManufacturerMSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin')"
    AnchorPeers:
      - Host: peer0.ma
 
  - &Distributor
    Name: Distributor
    ID: DistributorMSP
    MSPDir: ./crypto-config/peerOrganizations/distributor.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DistributorMSP.admin', 'DistributorMSP.client', 'DistributorMSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('DistributorMSP.admin', 'DistributorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DistributorMSP.admin')"

  - &Retailer
    Name: Retailer
    ID: RetailerMSP
    MSPDir: ./crypto-config/peerOrganizations/retailer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client', 'RetailerMSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RetailerMSP.admin')"

  - &Customer
    Name: Customer
    ID: CustomerMSP
    MSPDir: ./crypto-config/peerOrganizations/customer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CustomerMSP.admin', 'CustomerMSP.client', 'CustomerMSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('CustomerMSP.admin', 'CustomerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('CustomerMSP.admin')"

Application: &ApplicationDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Orderer: &OrdererDefaults
  OrderType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidations:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Profiles:
  SupplyChainOrderGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SupplyChainConsortiums:
        Organizations:
          - *Supplier
          - *Manufacturer
          - *Distributor
          - *Retailer
          - *Customer
  SupplyChainChannel:
    Consortiums: SupplyChainConsortiums
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *Supplier
          - *Manufacturer
          - *Distributor
          - *Retailer
          - *Customer
